trigger:
- master

pool: 'default'

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './build'
    ArtifactName: 'AUC-master-database'